// test exception
POST http://localhost:8600/users HTTP/1.1
Content-Type: application/json

null

###
// test exception
PUT  http://localhost:8600/users/search HTTP/1.1
Content-Type: application/json

{
  "page": "1",
  "pageSize": "10"
}

###

// and conditon with join conditions
POST   http://localhost:8600/users/search HTTP/1.1
Content-Type: application/json

{
  "page": "1",
  "pageSize": "10",
  "andConditions": [
    {
      "field": "nickname",
      "operator": "eq",
      "value": "ly"
    },
     {
      "field": "username",
      "operator": "like",
      "value": "ly"
    }
  ],
  "joinConditions": [
   {
     "joinField": "roles",
     "condition": {
      "field": "name",
      "operator": "eq",
      "value": "user"
    }
   }
  ]
}

###

DELETE http://localhost:8600 HTTP/1.1
Content-Type: application/json


###
# and condition for in operation

POST   http://localhost:8600/messages/search HTTP/1.1
Content-Type: application/json

{
  "page": "1",
  "pageSize": "10",
  "andConditions": [
    {
      "field": "id",
      "operator": "in",
      "value": [6,2,3]
    },
     {
      "field": "title",
      "operator": "in",
      "value": ["你好"]
    }
  ],
  "sortOrders":[
    {
      "field":"id",
      "ascending":false
    }
  ]
}


### 
// and condition with sort orders
POST   http://localhost:8600/messages/search HTTP/1.1
Content-Type: application/json

{
  "page": "1",
  "pageSize": "10",
  "andConditions": [
    {
      "field": "title",
      "operator": "eq",
      "value": "你好"
    }
  ],
  "sortOrders":[
    {
      "field":"id",
      "ascending":false
    }
  ]
}

### 

// and conditon with or condtion with sort orders
POST   http://localhost:8600/messages/search HTTP/1.1
Content-Type: application/json

{
  "page": "1",
  "pageSize": "10",
  "andConditions": [
    {
      "field": "id",
      "operator": "lt",
      "value": "2"
    }
  ],
  "orConditions":[
      {
      "field": "content",
      "operator": "like",
      "value": "time"
    }
  ],
  "sortOrders":[
    {
      "field":"id",
      "ascending":false
    }
  ]
}