server:
  port: 8600
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/quasar
    password: root
    username: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              basic-binder: TRACE
    web: TRACE

# custom properties
quasar:
  service:
    security:
      username: "admin"
      roles:
        - "USER"
        - "ADMIN"
    enabled: true
    url: 192.168.1.1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    config-url: /swagger-config.json
    url: /v3/api-docs
  #    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs
