server:
  port: 8600
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/quasar
    password: root
    username: root
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: '*'

# custom properties
quasar:
  service:
    security:
      username: "admin"
      roles:
        - "USER"
        - "ADMIN"
    enabled: true
    url: 192.168.1.1
