spring:
  application:
    name: quasar-api
  flyway:
    baseline-on-migrate: true
    out-of-order: true
    validate-on-migrate: false
  jpa:
    open-in-view: true

---

spring:
  profiles:
    # 选择环境
    active: dev